INSERT INTO ADMINISTRATOR(ACTIVE, USERNAME, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, CONTACT_PHONE, DATE_OF_BIRTH)
VALUES(TRUE, 'milica14', 'Milica', 'Milic', 'protic78223@gmail.com', 'fitness123', '0654384326', '2000-07-30')

INSERT INTO MEMBER(ACTIVE, USERNAME, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, CONTACT_PHONE, DATE_OF_BIRTH)
VALUES(TRUE, 'srdjo14', 'Srdjan', 'Protic', 'protic783@gmail.com', 'fitness', '0651384326', '2000-04-14')

INSERT INTO TRAINER(ACTIVE, USERNAME, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, CONTACT_PHONE, DATE_OF_BIRTH, AVG_GRADE)
VALUES(TRUE, 'fit14', 'Marko', 'Markovic', 'markovic134@gmail.com', 'fitnesss', '065784321', '1996-01-26', '4.50')

INSERT INTO TRAINING(NAME, TYPE, ABOUT_TRAINING, DURATION, TRAINER_ID)
VALUES('Trening za odraz', 'Plyometric', 'Medium-Hard', 35, 2)

INSERT INTO FITNESS_CENTER(ADDRESS, EMAIL, NAME, PHONE_NUMBER)
VALUES('Bulevar Cara Lazara 110', 'bull@gmail.com', 'Bull', 021456398)

INSERT INTO HALL(CAPACITY, LABEL, FITNESS_CENTER_ID)
VALUES('10', 'h1', 1)

INSERT INTO TERMS(PRICE, START_TRAINING, HALL_ID, TRAINER_ID, TRAINING_ID)
VALUES(250, '2021-16-5 17:20:00', 2, 3, 1)


